#!/bin/bash
#
# repository-installer This will install initial software for a fedora commons 3.8.1 server
# 
# chkconfig: 2345 9 20
# description: do things on firstboot to setup the server

randpw ()
{
    date +%s | sha256sum | base64 | head -c 7 ; echo
}
install-software()
{
    yum -y install git gettext sendmail
}
start()
{
        cd /opt;
        git clone https://github.com/dhinitiative/fedora-repository.git;
        chkconfig repository-installer off;
    return 0;
}

configure-ip()
{
    #
    # Note: the following variable will need to be updated for the type of ethernet interface on your host. 
    #        change the venet0:0 to whatever is on your machine (ie. eth0). 
    #
    IPADDR=`ifconfig -a venet0:0 | grep inet | awk '{print $2}' | awk -F: '{print $2}'`;
    sed -i "s|xxx\.xxx\.xxx\.xxx|${IPADDR}|g" /opt/fedora-repository/installer.sh
    return 0;
}

configure-email()
{
    sed -i "s|youremail@domain.com|<REPLACE WITH YOUR EMAIL>|g" /opt/fedora-repository/installer.sh
    return 0;
}

create-fuser-password()
{
    FUSER_PASS=`randpw`
    sed -i "s|fedora2014|$FUSER_PASS|g" /opt/fedora-repository/installer.sh
        return 0;
}
create-fedoradbpass()
{
    FDB_PASS=`randpw`
        sed -i "s|fedoradbpass|$FDB_PASS|g" /opt/fedora-repository/installer.sh
        return 0;
}
create-fedoraadminpass()
{
        FADMIN_PASS=`randpw`
        sed -i "s|fedoraadminpass|$FADMIN_PASS|g" /opt/fedora-repository/installer.sh
        return 0;
}
create-fgsadminpass()
{
       FGSADMIN_PASS=`randpw`
       sed -i "s|fgsadminpass|$FGSADMIN_PASS|g" /opt/fedora-repository/installer.sh
       return 0;
}
create-mysqlroot()
{
       MYSQL_PASS=`randpw`
       sed -i "s|mysqlroot|$MYSQL_PASS|g" /opt/fedora-repository/installer.sh
       return 0;
}
do-install()
{
    #
    # Note: it is assumed that we are installing this into /opt/fedora-repository
    #      update the path if you change this installation prefix
    #
        chmod 755 /opt/fedora-repository/installer.sh
    cd /opt/fedora-repository
        ./installer.sh >/opt/fedora-repository/installation.log 2>&1
}

case "$1" in
  start)
        echo $"Installing fedora-repository software in /opt.... "
    install-software
    start
    configure-ip
    configure-email
    create-fuser-password
    create-fedoradbpass
    create-fedoraadminpass
    create-fgsadminpass
    create-mysqlroot
    do-install
  ;;
  stop|status|restart|reload|force-reload)
   # do nothing
 ;;
esac
